build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*|[A-Z][a-zA-Z0-9]*' # Allow PascalCase for Composables
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][a-z0-9_]*)*' # Allow underscores in packages like use_case

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 100 # Increased from 60
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20

style:
  active: true
  WildcardImport:
    active: false # Disable for now to reduce noise, though usually better to fix
  ForbiddenComment:
    active: false # Allow TODOs

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Error
      - Throwable
      - RuntimeException
      - NullPointerException
      - IndexOutOfBoundsException
      # Removed Exception to allow catching it in repositories if rethrown/handled
